name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_ACCESS_KEY_ID: {{ "${{" }} secrets.AWS_ACCESS_KEY_ID {{ "}}" }}
  AWS_SECRET_ACCESS_KEY: {{ "${{" }} secrets.AWS_SECRET_ACCESS_KEY {{ "}}" }}
  AWS_REGION: {{ cookiecutter.AWS_REGION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.8
        terraform_wrapper: false

    - name: Terraform Version
      run: terraform version

    - name: Init Terraform
      run: terraform init

    - name: Create Plan
      id: plan
      run: terraform plan -no-color

  bump:
    name: Bump Version
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN:  {{ "${{" }} secrets.GITHUB_TOKEN {{ "}}" }}
          DEFAULT_BUMP: patch
          WITH_V: false