name: Deploy to AWS

on:
  release:
    types: [published]

env:
  AWS_ACCESS_KEY_ID: {{ "${{"  }} secrets.AWS_ACCESS_KEY_ID {{ "}}" }}
  AWS_SECRET_ACCESS_KEY: {{ "${{"  }} secrets.AWS_SECRET_ACCESS_KEY {{ "}}" }}
  AWS_REGION: {{ cookiecutter.AWS_REGION }}

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.8
        terraform_wrapper: false

    - name: Terraform Version
      run: terraform version

    - name: Init Terraform
      run: terraform init

    - name: Terraform Apply
      id: apply
      run: terraform apply --auto-approve